### ISSUE TITLE
Empty section between colons error

### ISSUE THREAD

**Issue by mikemocha** [jake-dog/xfinity-stream-linux#1]
Hello,

This excellent package no longer compiles. Testing on Ubuntu 24.04.1. Previously worked on Ubuntu 23.10.

After running the make command it goes through all the 7/7 steps then gets to "naming to docker.io/library/widevine-relr-patcher:0.1.0" then the make quits and I get "invalid spec :/root/patcher: empty section between colons..... [makefile:15 libwidevinecdm.so.patched] error 125

**Comment by jake-dog** [comment]
Please use `sudo -E make` instead of `sudo make`, which preserves the `$(PWD)` environment variable used in the makefile.

### Why? (If you're curious.)

I don't think this is OS specific.  I ran the instructions on ubuntu 24.04 and it completed successfully.

The makefile relies on the `$PWD` environment variable, which is unset (empty string) by default when running a command via sudo.  Adding the `-E` argument to the `sudo` command preserves the caller's environment.

**Comment by jake-dog** [comment]
The makefile now uses [`CURDIR`](https://www.gnu.org/software/make/manual/html_node/Quick-Reference.html) instead of `PWD`, which fixes this issue.
